### ISSUE TITLE
ordres du jour et procès verbal des commissions

### ISSUE THREAD

**Issue by sdis48** [SDIS62/prevarisc#625]
Je n'arrive pas à créer mes modèles d'ordre du jour et de procès verbal pour les sous-commissions.

Voilà le message que j'obtiens pour les ordres du jour 

Exception information:

Message: child infosDoss does not exist

Stack trace:
#0 /var/www/prevarisc/application/views/scripts/calendrier-des-commissions/generationodj.phtml(148): Segment->__get('infosDoss')
#1 /var/www/prevarisc/application/views/scripts/calendrier-des-commissions/generationodj.phtml(61): retrieveInfoDoss(Object(Segment), Array)
#2 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/View.php(108): include('/var/www/prevar...')
#3 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/View/Abstract.php(888): Zend_View->_run('/var/www/prevar...')
#4 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(905): Zend_View_Abstract->render('calendrier-des-...')
#5 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(926): Zend_Controller_Action_Helper_ViewRenderer->renderScript('calendrier-des-...', NULL)
#6 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(965): Zend_Controller_Action_Helper_ViewRenderer->render()
#7 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#8 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#9 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('generationodjAc...')
#10 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#12 /var/www/prevarisc/application/Bootstrap.php(24): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Application.php(382): Bootstrap->run()
#14 /var/www/prevarisc/public/index.php(75): Zend_Application->run()
#15 {main}

Request Parameters:

array (
  'controller' => 'calendrier-des-commissions',
  'action' => 'generationodj',
  'module' => 'default',
  'dateCommId' => '169',
)

**Comment by olivierbcr** [comment]
Bonjour,
Pourriez-vous m'envoyer votre modèle d'ordre du jour, pour que je puisse voir quels champs de fusion vous utilisez et leur ordonnancement, à obrochier@free.fr ?
Je peux également vous envoyer le notre pour vous aider.
Cordialement,

**Comment by 21Damien** [comment]
@olivierbcr  Bonjour, nous serions intéressés par le modèle de PV et de compte rendus si vous avez.

**Comment by olivierbcr** [comment]
```
Bonjour,
Nous avons réalisé environ 40 modèles à ce jour.
A quelle adresse courriel dois-je les envoyer ?
Cordialement,
```

**Comment by olivierbcr** [comment]
Le 15/11/2016 à 13:55, 21Damien a
      écrit :
    
    
      @olivierbcr Bonjour, nous serions
        intéressés par le modèle de PV et de compte rendus si vous avez.
      
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SDIS62/prevarisc","title":"SDIS62/prevarisc","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SDIS62/prevarisc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@21Damien in #625: @olivierbcr  Bonjour, nous serions intéressés par le modèle de PV et de compte rendus si vous avez. "}],"action":{"name":"View Issue","url":"https://github.com/SDIS62/prevarisc/issues/625#issuecomment-260633682"}}}
    
    Bonjour,
    
    Les avez-vous bien reçus ?
    
    
    Cordialement,
    --

**Comment by sdis48** [comment]
Bonjour,

 

Oui mais pas eu le temps de les regarder.

Je vous tiens au courant début 2016.

 

Ltn Claude DAUNIS

 

De : Cne Olivier BROCHIER [mailto:notifications@github.com] 
Envoyé : vendredi 9 décembre 2016 10:56
À : SDIS62/prevarisc
Cc : sdis48; Author
Objet : Re: [SDIS62/prevarisc] ordres du jour et procès verbal des commissions (#625)

 






Le 15/11/2016 à 13:55, 21Damien a
écrit :


@olivierbcr Bonjour, nous serions
intéressés par le modèle de PV et de compte rendus si vous avez.

—
You are receiving this because you were mentioned.
Reply to this email directly, view
it on GitHub, or mute
the thread.







{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SDIS62/prevarisc","title":"SDIS62/prevarisc","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SDIS62/prevarisc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@21Damien in #625: @olivierbcr Bonjour, nous serions intéressés par le modèle de PV et de compte rendus si vous avez. "}],"action":{"name":"View Issue","url":"https://github.com/SDIS62/prevarisc/issues/625#issuecomment-260633682"}}}

Bonjour,

Les avez-vous bien reçus ?


Cordialement,
--
